config/routes.rb
Rails.application.routes.draw do
  # verb '/path', to: 'controller#action', as: :prefix

  # GET "restaurants/38/reviews/new"
  # POST "restaurants/38/reviews"
  resources :restaurants
  resources :restaurants do
    resources :reviews, only: [ :new, :create ]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  CATEGORY = ["chinese", "italian", "japanese", "french", "belgian"]

  has_many :reviews, dependent: :destroy

  validates :name, presence: true
  validates :address, presence: true
  validates :phone_number, presence: true
  validates :category, inclusion: {in: CATEGORY}
end


# test = Restaurant.new(name: 'test', address: 'mefguro', phone_number: '0498320', category: 'Chinese')

app/models/review.rb
class Review < ApplicationRecord

  belongs_to :restaurant

  validates :rating, :content, presence: true
  validates :rating, inclusion: { in: (0..5).to_a }
  validates :restaurant_id, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    @restaurants = Restaurant.all
  end

  def show
    @restaurant = Restaurant.find(params[:id])
    @reviews = Review.where(restaurant_id: params[:id])
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def create
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new(review_params)
    @review.restaurant = @restaurant
    if @review.save
      redirect_to restaurant_path(@restaurant)
    else
      render 'new'
    end
  end

  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new
  end

private

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/index.html.erb
<div class="container py-5 text-decoration-none">
  <h1>Restaurantes</h1>
  <div class="cards">
    <% x = 0 %>
   <% @restaurants.each do |restaurant| %>
    <% link = "https://source.unsplash.com/#{x + 500}x100/?food" %>
    <% x += 1 %>
      <%= link_to restaurant_path(restaurant) do %>
        <div class="card-category my-2" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= link %>)">
          <h1><%= restaurant.name %></h1>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/restaurants/show.html.erb
<div class="banner" style="position: relative; background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://source.unsplash.com/1600x900/?restaurant);">
  <%= link_to restaurants_path do %>
    <i class="back fas fa-long-arrow-alt-left" style="position: absolute; top: 10px; left: 10px; font-size: 50px;"></i>
  <% end %>
  <div class="container">
    <h1><%= @restaurant.name %></h1>
    <p>address: <%= @restaurant.address %></p>
    <p>tel: <%= @restaurant.phone_number %></p>
    <!-- <#%= link_to class="btn btn-flat" %>  -->
  </div>
</div>

<div class="container">
  <h1 class="my-5">Reviews</h1>
  <% @reviews.each do |review| %>
  <div class="row my-5 border-bottom d-flex flex-column">
    <div class="mb-5">
      <h4><%= review.content %></h4>
    </div>
    <div>
      <% review.rating.times do %>
      <i class="fas fa-coffee"></i>
      <% end %>
    </div>
  </div>
  <% end %>
  <div>
    <%= link_to "+ write us a review　😊", new_restaurant_review_path(@restaurant)%>
  </div>
  <div class="footer">
    <div class="footer-links">
      <a href="#"><i class="fab fa-github"></i></a>
      <a href="#"><i class="fab fa-instagram"></i></a>
      <a href="#"><i class="fab fa-facebook"></i></a>
      <a href="#"><i class="fab fa-twitter"></i></a>
      <a href="#"><i class="fab fa-linkedin"></i></a>
    </div>
    <div class="footer-copyright">
      This page is powered by coffee <i class="fas fa-coffee"></i>
    </div>
  </div>

</div>

app/views/reviews/new.html.erb
<div class="page">
  <div class="centered card d-flex flex-column align-items-center py-3 px-5">
    <%= simple_form_for [@restaurant, @review] do |f| %>
    <h1 class="my-3">Write a review</h1>
    <%= f.input :content %>
    <%= f.input :rating %>
    <%= f.submit class: 'btn btn-light'%>
    <% end %>
  </div>
</div>